[package]
name = "arkomp"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.3"
libloading = "0.8.8"
log = "0.4.28"
rusty_spine = { path = "crates/rusty_spine3.8", features = [ "draw_functions", "mint" ], default-features = false }
shared = { path = "shared/" }
